package physics

import (
	"fmt"
	"strings"

	"github.com/jterrazz/universe/internal/config"
)

// Generate creates the physics.md content from a universe manifest.
// verifiedElements is the list of binaries confirmed to exist in the container.
// If nil, no elements section is generated.
func Generate(m config.UniverseManifest, verifiedElements []string) string {
	var b strings.Builder

	b.WriteString("# Physics of This Universe\n\n")
	b.WriteString("> This file describes the reality you exist in. It was generated by the Architect.\n\n")

	// Origin.
	b.WriteString("## Origin\n\n")
	b.WriteString(fmt.Sprintf("This universe was created from **%s**.\n\n", m.Physics.Origin))

	// Constants.
	b.WriteString("## Constants\n\n")
	b.WriteString("These are the fixed resource limits of your reality:\n\n")
	b.WriteString(fmt.Sprintf("| Constant | Value |\n"))
	b.WriteString(fmt.Sprintf("| --- | --- |\n"))
	b.WriteString(fmt.Sprintf("| CPU | %d cores |\n", m.Physics.Constants.CPU))
	b.WriteString(fmt.Sprintf("| Memory | %s |\n", m.Physics.Constants.Memory))
	b.WriteString(fmt.Sprintf("| Disk | %s |\n", m.Physics.Constants.Disk))
	b.WriteString(fmt.Sprintf("| Timeout | %s |\n", m.Physics.Constants.Timeout))
	b.WriteString("\n")

	// Laws.
	b.WriteString("## Laws\n\n")
	b.WriteString("These are invariant rules enforced by the environment:\n\n")
	b.WriteString(fmt.Sprintf("- **Network**: %s\n", m.Physics.Laws.Network))
	b.WriteString(fmt.Sprintf("- **Max processes**: %d\n", m.Physics.Laws.MaxProcesses))
	b.WriteString("\n")

	// Elements.
	b.WriteString("## Elements\n\n")
	if len(verifiedElements) == 0 {
		b.WriteString("No specific elements were declared. Use what's available in the origin.\n\n")
	} else {
		b.WriteString("These tools are available to you in this reality:\n\n")
		for _, elem := range verifiedElements {
			b.WriteString(fmt.Sprintf("- `%s`\n", elem))
		}
		b.WriteString("\n")
		b.WriteString("If a tool is not listed above, it does not exist in this world.\n\n")
	}

	// Gate (interactions).
	if len(m.Gate) > 0 {
		b.WriteString("## Interactions\n\n")
		b.WriteString("These bridges connect you to the Substrate (the outside world):\n\n")
		for _, g := range m.Gate {
			caps := "all"
			if len(g.Capabilities) > 0 {
				caps = strings.Join(g.Capabilities, ", ")
			}
			b.WriteString(fmt.Sprintf("- **%s** (via %s) — capabilities: %s\n", g.As, g.Source, caps))
		}
		b.WriteString("\n")
	}

	// Workspace.
	b.WriteString("## Workspace\n\n")
	b.WriteString("Your workspace is mounted at `/workspace`. This is where the project files live.\n\n")

	// Mind.
	b.WriteString("## Mind\n\n")
	b.WriteString("Your Mind is mounted at `/mind`. Read your personas, skills, knowledge, and playbooks to understand who you are.\n")

	return b.String()
}
